---
title: "MCAH Capstone"
author: "Sarah Johnson"
output: pdf_document
---

# Load libraries

```{r}
library(dplyr)
library(ggplot2)
library(tidyr)
library(naniar)
library(haven)
library(dagitty)
library(ggdag)
library(tableone)
library(survey)
library(srvyr)
library(kableExtra)
library(Hmisc)
library(Gmisc)
library(magick)
library(plotrix)
library(summarytools)
library(jtools)
library(lmtest)
library(aod)
library(interactions)
library(ggstance)

data_path <- "/Volumes/usts_data/data/"
```

# Load original data

```{r eval=FALSE}
data.all <- read_dta(paste(data_path,"./14818577/ICPSR_37229/DS0001/37229-0001-Data-REST.dta", sep = ""))
```

```{r}
load(paste(data_path, "data.all.Rda", sep = ""))
```

# Replace certain values with NAs

```{r, eval=FALSE}
rep_na_num <- c("Q1_13", "YRSSINCEFT", "AGEMOYR", "Q3_1", "Q3_2", "Q3_3", "Q4_10", "Q10_9", "Q12_10", "Q12_11", "Q12_16", "Q12_19", "AGESURGERY", "Q13_3", "Q16_10", "Q16_11", "Q16_12", "AGEFIRSTATTEMPT", "AGELASTATTEMPT", "Q17_7")

rep_na_other <- names(data.all)[!names(data.all) %in% c("IDCODE",rep_na_num)]
```

```{r, eval=FALSE}
rep_w_na_num <- function(x) {
  x[x %in% c(888,999)] = NA
  return(x)
}

data.all[rep_na_num] <- apply(data.all[rep_na_num], 2, rep_w_na_num)

rep_w_na_other <- function(x) {
  x[x %in% c(77,88,99)] = NA
  return(x)
}

data.all[rep_na_other] <- apply(data.all[rep_na_other], 2, rep_w_na_other)

all_but_time <- names(data.all)[names(data.all) != "TIMESUBMITTED"]
data.all[all_but_time] <- apply(data.all[all_but_time], 2, as.numeric)

save(data.all, file = paste(data_path, "data.all.raw.Rda", sep = ""))
```

```{r}
load(paste(data_path, "data.all.raw.Rda", sep = ""))
```


# Create discrimination variables

```{r }
data.all <- data.all %>% 
  mutate(disc.age = select(.,
                           Q17_4_1, 
                           Q17_5_1 , 
                           Q17_9_1 , 
                           Q21_8_1_1 , 
                           Q21_8_2_1 , 
                           Q21_8_3_1 , 
                           Q24_2_1) %>% 
           rowSums(na.rm = TRUE),
         disc.dis = select(.,
                           Q17_4_2 , 
                           Q17_5_2 , 
                           Q17_9_2 , 
                           Q21_8_1_2 , 
                           Q21_8_2_2 ,
                           Q21_8_3_2 , 
                           Q24_2_2) %>% 
           rowSums(na.rm = TRUE),
         disc.inc.educ = select(.,
                                Q17_4_3 ,
                                Q17_5_3 ,
                                Q17_9_3 ,
                                Q21_8_1_3 , 
                                Q21_8_2_3 , 
                                Q21_8_3_3 , 
                                Q24_2_3) %>% 
           rowSums(na.rm = TRUE),
         disc.race = select(.,
                            Q17_4_6 ,
                            Q17_5_6 ,
                            Q17_9_6 , 
                            Q21_8_1_6 , 
                            Q21_8_2_6 , 
                            Q21_8_3_6 , 
                            Q24_2_6) %>% 
           rowSums(na.rm = TRUE),
         disc.rel = select(.,
                           Q17_4_7 ,
                           Q17_5_7 , 
                           Q17_9_7 , 
                           Q21_8_1_7 ,
                           Q21_8_2_7 ,
                           Q21_8_3_7 ,
                           Q24_2_7) %>% 
           rowSums(na.rm = TRUE),
         disc.so = select(.,
                          Q17_4_8 ,
                          Q17_5_8 ,
                          Q17_9_8 , 
                          Q21_8_1_8 ,
                          Q21_8_2_8 , 
                          Q21_8_3_8 , 
                          Q24_2_8) %>% 
           rowSums(na.rm = TRUE),
         disc.other = select(.,
                             Q17_4_9 , 
                             Q17_5_9 , 
                             Q17_9_9 , 
                             Q21_8_1_9 , 
                             Q21_8_2_9 , 
                             Q21_8_3_9 , 
                             Q24_2_9) %>% 
           rowSums(na.rm = TRUE),
         disc.trans = select(.,
                             Q17_4TRANSGE ,
                             Q17_5TRANSGE , 
                             Q17_9TRANSGE ,
                             Q21_8_1TRANSGE , 
                             Q21_8_2TRANSGE , 
                             Q21_8_3TRANSGE ,
                             Q24_2TRANSGE) %>% 
           rowSums(na.rm = TRUE),)  %>% 
  mutate(disc.non.trans = select(.,
                                 disc.age ,
                                 disc.dis ,
                                 disc.inc.educ , 
                                 disc.race , 
                                 disc.rel , 
                                 disc.so , 
                                 disc.other) %>% 
           rowSums(na.rm = TRUE),)
```

# Create affirmation variables

```{r}
data.all <- data.all %>%
  mutate(saab = factor(Q2_1 - 1,
                       labels = c("AFAB",
                                  "AMAB"))) %>%
  mutate(affirm.provider = ((Q11_4 == 2) | (Q11_4 == 3) | 
                              (Q11_7 == 2) | (Q11_7 == 3)),
         affirm.family = (-1*FAMSUPPORT3 + 3),
         affirm.id.name = (-1*Q10_13 + 3),
         affirm.id.gender = (-1*Q10_15 + 3),
         Q12_8eq9_1 = Q12_8_1 == Q12_9_1,
         Q12_8eq9_2 = Q12_8_2 == Q12_9_2,
         Q12_8eq9_3 = Q12_8_3 == Q12_9_3,
         Q12_15_1new = (saab == "AFAB")&((Q12_15_1 == 1) | (Q12_15_1 == 4)),
         Q12_15_2new = (saab == "AFAB")&((Q12_15_2 == 1) | (Q12_15_2 == 4)),
         Q12_15_3new = (saab == "AFAB")&((Q12_15_3 == 1) | (Q12_15_3 == 4)),
         Q12_15_4new = (saab == "AFAB")&((Q12_15_4 == 1) | (Q12_15_4 == 4)),
         Q12_15_5new = (saab == "AFAB")&((Q12_15_5 == 1) | (Q12_15_5 == 4)),
         Q12_18_1new = (saab == "AMAB")&((Q12_18_1 == 1) | (Q12_18_1 == 4)),
         Q12_18_2new = (saab == "AMAB")&((Q12_18_2 == 1) | (Q12_18_2 == 4)),
         Q12_18_3new = (saab == "AMAB")&((Q12_18_3 == 1) | (Q12_18_3 == 4)),
         Q12_18_4new = (saab == "AMAB")&((Q12_18_4 == 1) | (Q12_18_4 == 4)),
         Q12_18_5new = (saab == "AMAB")&((Q12_18_5 == 1) | (Q12_18_5 == 4)),
         Q12_18_6new = (saab == "AMAB")&((Q12_18_6 == 1) | (Q12_18_6 == 4)),
         Q12_18_7new = (saab == "AMAB")&((Q12_18_7 == 1) | (Q12_18_7 == 4)),
         Q12_18_8new = (saab == "AMAB")&((Q12_18_8 == 1) | (Q12_18_8 == 4)),
         Q12_18_9new = (saab == "AMAB")&((Q12_18_9 == 1) | (Q12_18_9 == 4)),
         Q12_18_10new = (saab == "AMAB")&((Q12_18_10 == 1) | (Q12_18_10 == 4)),
         ) %>%
  mutate(Q12_8eq9_all = Q12_8eq9_1 & Q12_8eq9_2 & Q12_8eq9_3,
         Q12_15or18_all = ((saab == "AFAB") &
                         (Q12_15_1new & Q12_15_2new & Q12_15_3new & 
                            Q12_15_4new & Q12_15_5new)) | 
           ((saab == "AMAB") &
                         (Q12_18_1new & Q12_18_2new & Q12_18_3new & 
                            Q12_18_4new & Q12_18_5new & Q12_18_6new &
                            Q12_18_7new & Q12_18_8new & Q12_18_9new &
                            Q12_18_10new)),
  ) %>% mutate(Q12_8eq9_some = (Q12_8eq9_1 | Q12_8eq9_2 | Q12_8eq9_3) & (!Q12_8eq9_all),
               Q12_15or18_some = (((saab == "AFAB") & ((Q12_15_1new | Q12_15_2new | Q12_15_3new |
                                          Q12_15_4new | Q12_15_5new))) | 
           ((saab == "AMAB") &
                         ((Q12_18_1new | Q12_18_2new | Q12_18_3new | 
                            Q12_18_4new | Q12_18_5new | Q12_18_6new |
                            Q12_18_7new | Q12_18_8new | Q12_18_9new |
                            Q12_18_10new)))) & (!Q12_15or18_all),
    
  ) %>%
  mutate(affirm.hormone = (Q12_8eq9_all*2 + Q12_8eq9_some*1),
         affirm.med.surg = (Q12_15or18_all*2 + Q12_15or18_some*1),
         ) %>%
  mutate(affirm.total = select(.,
                                 affirm.provider,
                                 affirm.family,
                                 affirm.id.name, 
                                 affirm.id.gender, 
                                 affirm.hormone, 
                                 affirm.med.surg) %>% 
           rowSums(na.rm = TRUE),) %>%
  mutate(affirm.total.cat = factor(cut(affirm.total, breaks = c(-0.5,2.5,4.5,10.5)),
                                   labels = c("Low Overall Affirmation",
                                              "Medium Overall Affirmation",
                                              "High Overall Affirmation")),
         ) %>%
  mutate(affirm.provider = factor(affirm.provider,
                                  labels = c("Not knowledgeable/Not sure/No provider",
                                             "Knowledgeable")),
         affirm.family = factor(affirm.family,
                                labels = c("Unsupportive",
                                           "Neutral",
                                           "Supportive")),
         affirm.id.name = factor(affirm.id.name,
                             labels = c("None",
                                        "Some",
                                        "All")),
         affirm.id.gender = factor(affirm.id.gender,
                             labels = c("None",
                                        "Some",
                                        "All")),
         affirm.hormone = factor(affirm.hormone,
                                         labels = c("None",
                                                    "Some",
                                                    "All")),
         affirm.med.surg = factor(affirm.med.surg,
                                         labels = c("None",
                                                    "Some",
                                                    "All")),)

```

# Create factor variables

```{r }
data.all <- data.all %>%
  mutate(military = factor(Q2_17 != 1,
                           labels = c("Not Military",
                                      "Military")),
         K6severe = factor(KESSLER6CAT, 
                          labels = c("K6 Score < 13", 
                                     "K6 Score 13+")),
         kessler6 = 1*KESSLER6,
         suicidal = factor(Q16_1,
                           labels = c("No Suicidal Ideation",
                                      "Suicidal Ideation")),
         orientation = factor(Q2_8CAT7, 
                                     labels = c("Asexual",
                                                "Bisexual",
                                                "Gay/Lesbian/SGL",
                                                "Heterosexual/Straight",
                                                "Pansexual",
                                                "Queer",
                                                "S.O. not listed")),
         disc.trans.quantile = cut(disc.trans, 
                                   breaks = c(quantile(disc.trans,
                                                       probs = seq(0, 1, by=0.5))),
                                                       include.lowest = TRUE, 
                                   labels = c("Trans Disc. Score At or Below Median",
                                              "Trans Disc. Score Above Median")),
         citizenship = factor(CITIZEN3,
                              labels = c("U.S. citizen",
                                         "Documented resident",
                                         "Undocumented resident")),
         passing = factor(VISUALCONFORMITY,
                          labels = c("Not Passing as Cisgender",
                                     "Somewhat Passing as Cisgender",
                                     "Passing as Cisgender")),
         outness = factor(OUTNESS,
                          labels = c("None",
                                     "Some",
                                     "Most",
                                     "All")),
         race = factor(RACEACS2,
                       labels = c("Alaska Native/American Indian alone",
                                  "Asian/Native Hawaiian/Pacific Islander alone",
                                  "Biracial/Multiracial/Not listed",
                                  "Black/African American alone",
                                  "Latino/a/Hispanic alone",
                                  "White/Middle Eastern/North African alone")),
         age = Q2_13,
         education = factor(EDUCATION4,
                            labels = c("Less than high school",
                                       "High school grad (incl. GED)",
                                       "Some college (no degree)/Associate's",
                                       "Bachelor's degree or higher")),
         disability = factor(ANYACSDIS, 
                             labels = c("No Disability",
                                        "Disability")),
         religious = factor(RELIGIOUS, 
                            labels = c("Not religious/spiritual",
                                       "Religious/Spiritual")),
         gender = factor(GENDER5,
                         labels = c("Crossdresser",
                                    "Trans woman",
                                    "Trans man",
                                    "AFAB GQ/NB",
                                    "AMAB GQ/NB")),
         nonbinary = factor(GENDER2,
                            labels = c("Trans",
                                       "GQ/NB")),
         censusdivision = factor(CENSUSDIVISION,
                                 labels = c("No census division",
                                            "New England",
                                            "Middle Atlantic",
                                            "East North Central",
                                            "West North Central",
                                            "South Atlantic",
                                            "East South Central",
                                            "West South Central",
                                            "Mountain",
                                            "Pacific")),
         poverty = factor(POVERTY,
                          labels = c("Not Living At/Near Poverty",
                                     "Living At/Near Poverty")),
         overall = "Overall"
         )

# Re-level factor variables where needed
data.all$race <- relevel(data.all$race, ref = "White/Middle Eastern/North African alone")
data.all$orientation <- relevel(data.all$orientation, ref = "Heterosexual/Straight")
#data.all$education <- relevel(data.all$education, ref = "High school grad (incl. GED)")
```


```{r}
label(data.all$kessler6) <- "Kessler 6 Score" 
label(data.all$K6severe) <- "Severe Kessler 6"
label(data.all$suicidal) <- "Suicidal Ideation"
label(data.all$censusdivision) <-  "Census Division"
label(data.all$citizenship) <- "Citizenship"
label(data.all$passing) <- "Passing as Cisgender"
label(data.all$outness) <- "Outness" 
label(data.all$orientation) <-  "Sexual Orientation"
label(data.all$race) <-  "Race"
label(data.all$age) <-  "Age"
label(data.all$education) <-  "Education"
label(data.all$disability) <-  "Disability"
label(data.all$military) <- "Military"  
label(data.all$religious) <-  "Religious"
label(data.all$gender) <-  "Gender"
label(data.all$nonbinary) <-  "NB Gender"
label(data.all$disc.non.trans) <-  "Non-Trans Discrimination"
label(data.all$disc.trans) <- "Trans Discrimination" 
label(data.all$disc.trans.quantile) <- "Trans Discrimination by Median"
label(data.all$affirm.total) <- "Total Affirmation"
label(data.all$affirm.total.cat) <- "Total Affirmation (Categorical)"
label(data.all$affirm.provider) <- "Knowledgeable Provider"
label(data.all$affirm.family) <- "Family Affirmation"
label(data.all$affirm.id.name) <- "Correct Name on IDs"
label(data.all$affirm.id.gender) <- "Correct Gender on IDs"
label(data.all$affirm.hormone) <- "Hormonal/Counseling Affirmation"
label(data.all$affirm.med.surg) <- "Medical/Surgical Affirmation"
```

# Create include variable

```{r}
data.all <- data.all %>% mutate(include = 
                                  (gender != "Crossdresser") &
                                  (nonbinary == "GQ/NB") &
                                  (!is.na(suicidal))) 

save(data.all, file = paste(data_path, "data.all.Rda", sep = ""))
```


# Univariate Distributions

```{r}
data.nb <- data.all  %>% filter(include == TRUE)

ggplot(data = data.nb, aes(x = disc.trans)) +
  geom_histogram(binwidth = 1)

ggplot(data = data.nb, aes(x = disc.non.trans)) +
  geom_histogram(binwidth = 1)

ggplot(data = data.nb, aes(x = affirm.total)) +
  geom_bar()

ggplot(data = data.nb, aes(x = affirm.total.cat)) +
  geom_bar()

ggplot(data = data.nb, aes(x = affirm.provider)) +
  geom_bar()

ggplot(data = data.nb, aes(x = affirm.family)) +
  geom_bar()

ggplot(data = data.nb, aes(x = affirm.id.name)) +
  geom_bar()

ggplot(data = data.nb, aes(x = affirm.id.gender)) +
  geom_bar()

ggplot(data = data.nb, aes(x = affirm.hormone)) +
  geom_bar()
  
ggplot(data = data.nb, aes(x = affirm.med.surg)) +
  geom_bar()
```

```{r}
p1 <- ggplot(data = data.nb, aes(x = disc.trans, y = ..density..)) +
  geom_histogram(binwidth = 1, fill = "darkblue", colour = "white") +
  labs(x = "Trans-Based Discrimination Score",
       y = element_blank(),
       title = "Distribution of Exposure (Discrimination)") +
  scale_x_continuous(breaks = 0:7) +
  scale_y_continuous(labels = scales::percent)
p1
```

```{r}
p2 <- ggplot(data = data.nb, aes(x = affirm.total, y = ..density..)) +
  geom_histogram(binwidth = 1,fill = "darkblue", colour = "white") +
  labs(x = "Gender Affirmation Score",
       y = element_blank(),
       title = "Distribution of Moderator (Affirmation)") +
  scale_x_continuous(breaks = 0:11) +
  scale_y_continuous(labels = scales::percent)
p2
```

```{r}
p3 <- ggplot(data = data.nb, aes(x = age, y = ..density..)) +
  geom_histogram(binwidth = 5, fill = "darkblue", colour = "white") +
  labs(x = "Trans-Based Discrimination Score",
       y = element_blank(),
       title = "Age") +
  scale_x_continuous(breaks = seq(0,100,10)) #+
  #scale_y_continuous(labels = scales::percent)
p3
```



```{r}
sink("FreqDiscTrans.txt")
freq(data.nb$disc.trans)
sink()

sink("FreqAffirmTotal.txt")
freq(data.nb$affirm.total)
sink()

sink("FreqAffirmTotalCat.txt")
freq(data.nb$affirm.total.cat)
sink()

tab.disc.affirm <- table(data.nb$disc.trans,data.nb$affirm.total.cat)
sink("TableDiscAffirmCat.txt")
print(tab.disc.affirm)
sink()

sink("PropTableDiscAffirmCat.txt")
round(prop.table(tab.disc.affirm)*100, 2)
sink()
```



# Create survey design

```{r}
data.design <- data.all %>%
  select(disc.trans,
         disc.trans.quantile,
         K6severe,
         suicidal,
         gender, 
         nonbinary,
         saab,
         disc.non.trans,
         affirm.provider,
         affirm.family,
         affirm.id.name,
         affirm.id.gender,
         affirm.hormone,
         affirm.med.surg,
         affirm.total,
         affirm.total.cat,
         age,
         race,
         education,
         poverty,
         citizenship,
         censusdivision,
         passing,
         outness,
         orientation,
         disability,
         military,
         religious,
         SURVEYFULLWEIGHT,
         include)

save(data.design, file = paste(data_path, "data.design.Rda", sep = ""))
```

```{r}
USTS.design.raw <- svydesign(ids = ~1,
                     weights = ~SURVEYFULLWEIGHT,
                     nest = FALSE,
                     data = data.design)
```

```{r}
summary(USTS.design.raw)
sum(weights(USTS.design.raw, "sampling") == 0 )
```

# Subset the dataset using exclusion criteria

```{r}
USTS.design <- subset(USTS.design.raw, include == TRUE)
summary(USTS.design)
```


# Compute basic statistics

```{r}
svymean(~age, USTS.design, na.rm = T)
confint(svymean(~age, USTS.design, na.rm = T))

svyby(~age, ~gender, USTS.design, svymean, na.rm = T)
```

```{r}
cors <- svycor(~ disc.trans + 
         affirm.total + 
        as.numeric(affirm.total.cat)+ 
         as.numeric(affirm.provider)+ 
         as.numeric(affirm.family)+ 
         as.numeric(affirm.id.name)+ 
         as.numeric(affirm.id.gender)+
         as.numeric(affirm.hormone)+ 
         as.numeric(affirm.med.surg), design = USTS.design, na.rm = T)
sum(abs(cors$cors)[1,] > 0.2) - 1
```


```{r}
svymean(~disc.trans, USTS.design, na.rm = T)
confint(svymean(~disc.trans, USTS.design, na.rm = T))

svyby(~disc.trans, ~gender, USTS.design, svymean, na.rm = T)
```

```{r}
svymean(~K6severe, USTS.design, na.rm = T)
confint(svymean(~K6severe, USTS.design, na.rm = T))

svyby(~K6severe, ~gender, USTS.design, svymean, na.rm = T)
```

```{r}
svymean(~suicidal, USTS.design, na.rm = T)
confint(svymean(~suicidal, USTS.design, na.rm = T))

svyby(~suicidal, ~gender, USTS.design, svymean, na.rm = T)
```

```{r}
svymean(~affirm.total, USTS.design, na.rm = T)
confint(svymean(~affirm.total, USTS.design, na.rm = T))

svyby(~affirm.total, ~gender, USTS.design, svymean, na.rm = T)
```

```{r}
svymean(~affirm.total.cat, USTS.design, na.rm = T)
confint(svymean(~affirm.total.cat, USTS.design, na.rm = T))

svyby(~affirm.total.cat, ~gender, USTS.design, svymean, na.rm = T)
```

```{r}
svymean(~affirm.provider, USTS.design, na.rm = T)
confint(svymean(~affirm.provider, USTS.design, na.rm = T))

svyby(~affirm.provider, ~gender, USTS.design, svymean, na.rm = T)
```

```{r}
svymean(~poverty, USTS.design, na.rm = T)
confint(svymean(~poverty, USTS.design, na.rm = T))

svyby(~poverty, ~gender, USTS.design, svymean, na.rm = T)
```

```{r}
svymean(~race, USTS.design, na.rm = T)
confint(svymean(~race, USTS.design, na.rm = T))

svyby(~race, ~gender, USTS.design, svymean, na.rm = T)
```

```{r}
svymean(~education, USTS.design, na.rm = T)
confint(svymean(~education, USTS.design, na.rm = T))

svyby(~education, ~gender, USTS.design, svymean, na.rm = T)
```

```{r}
svymean(~outness, USTS.design, na.rm = T)
confint(svymean(~outness, USTS.design, na.rm = T))

svyby(~outness, ~gender, USTS.design, svymean, na.rm = T)
```

```{r}
svymean(~passing, USTS.design, na.rm = T)
confint(svymean(~passing, USTS.design, na.rm = T))

svyby(~passing, ~gender, USTS.design, svymean, na.rm = T)
```

```{r}
svymean(~censusdivision, USTS.design, na.rm = T)
confint(svymean(~censusdivision, USTS.design, na.rm = T))

svyby(~censusdivision, ~gender, USTS.design, svymean, na.rm = T)
```

```{r}
svymean(~orientation, USTS.design, na.rm = T)
confint(svymean(~orientation, USTS.design, na.rm = T))

svyby(~orientation, ~gender, USTS.design, svymean, na.rm = T)
```

```{r}
svymean(~citizenship, USTS.design, na.rm = T)
confint(svymean(~citizenship, USTS.design, na.rm = T))

svyby(~citizenship, ~gender, USTS.design, svymean, na.rm = T)
```

```{r}
svymean(~disability, USTS.design, na.rm = T)
confint(svymean(~disability, USTS.design, na.rm = T))

svyby(~disability, ~gender, USTS.design, svymean, na.rm = T)
```

```{r}
svymean(~military, USTS.design, na.rm = T)
confint(svymean(~military, USTS.design, na.rm = T))

svyby(~military, ~gender, USTS.design, svymean, na.rm = T)
```

```{r}
svymean(~religious, USTS.design, na.rm = T)
confint(svymean(~religious, USTS.design, na.rm = T))

svyby(~religious, ~gender, USTS.design, svymean, na.rm = T)
```

```{r}
svymean(~disc.non.trans, USTS.design, na.rm = T)
confint(svymean(~disc.non.trans, USTS.design, na.rm = T))

svyby(~disc.non.trans, ~gender, USTS.design, svymean, na.rm = T)
```

# Models

```{r}
# Crude model
glm.crude <- svyglm(suicidal ~ disc.trans,
                              family = quasibinomial(),
                              data   = data.design,
                              design = USTS.design)

summary(glm.crude)

#exponentiated ORs
exp(coefficients(glm.crude))

#exponentiated 95 CIs
exp(confint(glm.crude))

#better output
summ(glm.crude, exp = T, confint = T)

sink("ModelCrude.txt")
summ(glm.crude, exp = T, confint = T)
sink()
```

```{r}
# Crude model
glm.crude.affirm <- svyglm(suicidal ~ affirm.total,
                              family = quasibinomial(),
                              data   = data.design,
                              design = USTS.design)

#better output
summ(glm.crude.affirm, exp = T, confint = T)

sink("ModelCrudeAffirm.txt")
summ(glm.crude.affirm, exp = T, confint = T)
sink()
```

```{r}
# Crude model
glm.crude.affirm.cat <- svyglm(suicidal ~ affirm.total.cat,
                              family = quasibinomial(),
                              data   = data.design,
                              design = USTS.design)

#better output
summ(glm.crude.affirm.cat, exp = T, confint = T)

sink("ModelCrudeAffirmCat.txt")
summ(glm.crude.affirm.cat, exp = T, confint = T)
sink()
```

```{r}
# Crude model
glm.crude.affirm.all <- svyglm(suicidal ~ affirm.provider +
                                 affirm.family +
                                 affirm.id.name +
                                 affirm.id.gender +
                                 affirm.hormone +
                                 affirm.med.surg,
                              family = quasibinomial(),
                              data   = data.design,
                              design = USTS.design)

#better output
summ(glm.crude.affirm.all, exp = T, confint = T)

sink("ModelCrudeAffirmAll.txt")
summ(glm.crude.affirm.all, exp = T, confint = T)
sink()
```

```{r}
# Crude model
glm.crude.provider <- svyglm(suicidal ~ affirm.provider,
                              family = quasibinomial(),
                              data   = data.design,
                              design = USTS.design)

#better output
summ(glm.crude.provider, exp = T, confint = T)

sink("ModelCrudeProvider.txt")
summ(glm.crude.provider, exp = T, confint = T)
sink()
```

```{r}
# Crude model
glm.crude.id.name <- svyglm(suicidal ~ affirm.id.name,
                              family = quasibinomial(),
                              data   = data.design,
                              design = USTS.design)

#better output
summ(glm.crude.id.name, exp = T, confint = T)

sink("ModelCrudeIDsName.txt")
summ(glm.crude.id.name, exp = T, confint = T)
sink()
```

```{r}
# Crude model
glm.crude.id.gender <- svyglm(suicidal ~ affirm.id.gender,
                              family = quasibinomial(),
                              data   = data.design,
                              design = USTS.design)

#better output
summ(glm.crude.id.gender, exp = T, confint = T)

sink("ModelCrudeIDsGender.txt")
summ(glm.crude.id.gender, exp = T, confint = T)
sink()
```

```{r}
# Crude model
glm.crude.family <- svyglm(suicidal ~ affirm.family,
                              family = quasibinomial(),
                              data   = data.design,
                              design = USTS.design)

#better output
summ(glm.crude.family, exp = T, confint = T)

sink("ModelCrudeFamily.txt")
summ(glm.crude.family, exp = T, confint = T)
sink()
```

```{r}
# Crude model
glm.crude.hormone <- svyglm(suicidal ~ affirm.hormone,
                              family = quasibinomial(),
                              data   = data.design,
                              design = USTS.design)

#better output
summ(glm.crude.hormone, exp = T, confint = T)

sink("ModelCrudeHormone.txt")
summ(glm.crude.hormone, exp = T, confint = T)
sink()
```

```{r}
# Crude model
glm.crude.med <- svyglm(suicidal ~ affirm.med.surg,
                              family = quasibinomial(),
                              data   = data.design,
                              design = USTS.design)

#better output
summ(glm.crude.med, exp = T, confint = T)

sink("ModelCrudeMedical.txt")
summ(glm.crude.med, exp = T, confint = T)
sink()
```

```{r}
# Crude model
glm.crude.all <- svyglm(suicidal ~ disc.trans +
                          affirm.provider +
                          affirm.family +
                          affirm.id.name +
                          affirm.id.gender +
                          affirm.hormone +
                          affirm.med.surg,
                              family = quasibinomial(),
                              data   = data.design,
                              design = USTS.design)

#better output
summ(glm.crude.all, exp = T, confint = T)

sink("ModelCrudeAll.txt")
summ(glm.crude.all, exp = T, confint = T)
sink()
```


```{r}
# Intermediate model - discrimination only
glm.int.disc <- svyglm(suicidal ~ disc.trans +
                         disc.non.trans +
                         age +
                         race +
                         education +
                         poverty +
                         citizenship +
                         religious +
                         military +
                         disability +
                         saab +
                         passing +
                         outness +
                         orientation,
                             family = quasibinomial(),
                             data   = data.design,
                             design = USTS.design)

summ(glm.int.disc, exp = T, confint = T)

sink("ModelIntDisc.txt")
summ(glm.int.disc, exp = T, confint = T)
sink()
```

```{r}
# Intermediate model - affirm total
glm.int.affirm <- svyglm(suicidal ~ disc.trans +
                           affirm.total +
                           disc.non.trans +
                         age +
                         race +
                         education +
                         poverty +
                         citizenship +
                         religious +
                         military +
                         disability +
                         saab +
                         passing +
                         outness +
                         orientation,
                             family = quasibinomial(),
                             data   = data.design,
                             design = USTS.design)

summ(glm.int.affirm, exp = T, confint = T)

sink("ModelIntAffirm.txt")
summ(glm.int.affirm, exp = T, confint = T)
sink()
```

```{r}
# Intermediate model - affirm total cat
glm.int.affirm.cat <- svyglm(suicidal ~ disc.trans +
                               affirm.total.cat +
                               disc.non.trans +
                               age +
                               race +
                               education +
                               poverty +
                               citizenship +
                               religious +
                               military +
                               disability +
                               saab +
                               passing +
                               outness +
                               orientation,
                             family = quasibinomial(),
                             data   = data.design,
                             design = USTS.design)

summ(glm.int.affirm.cat, exp = T, confint = T)

sink("ModelIntAffirmCat.txt")
summ(glm.int.affirm.cat, exp = T, confint = T)
sink()
```

```{r}
# Intermediate model - all
glm.int.all <- svyglm(suicidal ~ disc.trans +
                        affirm.family +
                        affirm.provider +
                        affirm.id.name +
                        affirm.id.gender +
                        affirm.hormone +
                        affirm.med.surg +
                        disc.non.trans +
                         age +
                         race +
                         education +
                         poverty +
                         citizenship +
                         religious +
                         military +
                         disability +
                         saab +
                         passing +
                         outness +
                         orientation,
                             family = quasibinomial(),
                             data   = data.design,
                             design = USTS.design)

summ(glm.int.all, exp = T, confint = T)

sink("ModelIntAll.txt")
summ(glm.int.all, exp = T, confint = T)
sink()
```

```{r}
# Interaction model - affirm total only
glm.ixn.affirm <- svyglm(suicidal ~ disc.trans*affirm.total +
                           disc.non.trans +
                           age +
                           race +
                           education +
                           poverty +
                           citizenship +
                           religious +
                           military +
                           disability +
                           saab +
                           passing +
                           outness +
                           orientation,
                             family = quasibinomial(),
                             data   = data.design,
                             design = USTS.design)

summ(glm.ixn.affirm, exp = T, confint = T)

sink("ModelIxnAffirm.txt")
summ(glm.ixn.affirm, exp = T, confint = T)
sink()
```

```{r}
# Interaction model - affirm total only
glm.ixn.affirm.cat <- svyglm(suicidal ~ disc.trans*affirm.total.cat +
                           disc.non.trans +
                           age +
                           race +
                           education +
                           poverty +
                           citizenship +
                           religious +
                           military +
                           disability +
                           saab +
                           passing +
                           outness +
                           orientation,
                             family = quasibinomial(),
                             data   = data.design,
                             design = USTS.design)

summ(glm.ixn.affirm.cat, exp = T, confint = T)

sink("ModelIxnAffirmCat.txt")
summ(glm.ixn.affirm.cat, exp = T, confint = T)
sink()
```

```{r}
# Interaction model - provider only
glm.ixn.provider <- svyglm(suicidal ~ disc.trans*affirm.provider +
                           disc.non.trans +
                           age +
                           race +
                           education +
                           poverty +
                           citizenship +
                           religious +
                           military +
                           disability +
                           saab +
                           passing +
                           outness +
                           orientation,
                             family = quasibinomial(),
                             data   = data.design,
                             design = USTS.design)

summ(glm.ixn.provider, exp = T, confint = T)

sink("ModelIxnProvider.txt")
summ(glm.ixn.provider, exp = T, confint = T)
sink()
```

```{r}
# Interaction model - family only
glm.ixn.family <- svyglm(suicidal ~ disc.trans*affirm.family +
                           disc.non.trans +
                           age +
                           race +
                           education +
                           poverty +
                           citizenship +
                           religious +
                           military +
                           disability +
                           saab +
                           passing +
                           outness +
                           orientation,
                             family = quasibinomial(),
                             data   = data.design,
                             design = USTS.design)

summ(glm.ixn.family, exp = T, confint = T)

sink("ModelIxnFamily.txt")
summ(glm.ixn.family, exp = T, confint = T)
sink()
```

```{r}
# Interaction model - Name IDs only
glm.ixn.id.name <- svyglm(suicidal ~ disc.trans*affirm.id.name +
                           disc.non.trans +
                           age +
                           race +
                           education +
                           poverty +
                           citizenship +
                           religious +
                           military +
                           disability +
                           saab +
                           passing +
                           outness +
                           orientation,
                             family = quasibinomial(),
                             data   = data.design,
                             design = USTS.design)

summ(glm.ixn.id.name, exp = T, confint = T)

sink("ModelIxnIDsName.txt")
summ(glm.ixn.id.name, exp = T, confint = T)
sink()
```

```{r}
# Interaction model - Gender IDs only
glm.ixn.id.gender <- svyglm(suicidal ~ disc.trans*affirm.id.gender +
                              disc.non.trans +
                           age +
                           race +
                           education +
                           poverty +
                           citizenship +
                           religious +
                           military +
                           disability +
                           saab +
                           passing +
                           outness +
                           orientation,
                             family = quasibinomial(),
                             data   = data.design,
                             design = USTS.design)

summ(glm.ixn.id.gender, exp = T, confint = T)

sink("ModelIxnIDsGender.txt")
summ(glm.ixn.id.gender, exp = T, confint = T)
sink()
```

```{r}
# Interaction model - hormones/counseling only
glm.ixn.hormone <- svyglm(suicidal ~ disc.trans*affirm.hormone +
                            disc.non.trans +
                           age +
                           race +
                           education +
                           poverty +
                           citizenship +
                           religious +
                           military +
                           disability +
                           saab +
                           passing +
                           outness +
                           orientation,
                             family = quasibinomial(),
                             data   = data.design,
                             design = USTS.design)

summ(glm.ixn.hormone, exp = T, confint = T)

sink("ModelIxnHormone.txt")
summ(glm.ixn.hormone, exp = T, confint = T)
sink()
```

```{r}
# Interaction model - medical/surgical only
glm.ixn.med <- svyglm(suicidal ~ disc.trans*affirm.med.surg +
                        disc.non.trans +
                           age +
                           race +
                           education +
                           poverty +
                           citizenship +
                           religious +
                           military +
                           disability +
                           saab +
                           passing +
                           outness +
                           orientation,
                             family = quasibinomial(),
                             data   = data.design,
                             design = USTS.design)

summ(glm.ixn.med, exp = T, confint = T)

sink("ModelIxnMed.txt")
summ(glm.ixn.med, exp = T, confint = T)
sink()
```


```{r}
# Interaction model - affirm total only - rm
glm.ixn.affirm.rm <- svyglm(suicidal ~ disc.trans*affirm.total +
                              disc.non.trans +
                              age +
                              race +
                              education +
                              poverty +
                              disability +
                              saab +
                              passing,
                             family = quasibinomial(),
                             data   = data.design,
                             design = USTS.design)

summ(glm.ixn.affirm.rm, exp = T, confint = T)



sink("ModelIxnAffirmRm.txt")
summ(glm.ixn.affirm.rm, exp = T, confint = T)
sink()

#lrtest(glm.ixn.affirm.rm.religious, glm.ixn.affirm)
#wald.test(coef(glm.ixn.affirm.rm), Sigma = vcov(glm.ixn.affirm.rm), Terms = ??)
```

```{r}
sim.slope <- sim_slopes(glm.ixn.affirm.rm, pred = disc.trans, modx = affirm.total, modx.values = 0:11)
sim.slope
sim.slope.tidy <- tidy(sim.slope)
sim.slope.tidy
save(sim.slope.tidy, file = "sim.slope.tidy.Rda")
plot(sim.slope)
```

```{r}
sim.slopes.exp <- sim.slope.tidy %>% 
  mutate(estimate = round(exp(estimate),2),
         conf.low = round(exp(conf.low),2),
         conf.high = round(exp(conf.high),2),
         p.value = round(p.value,4)) %>%
  select(modx.value, estimate, conf.low, conf.high, p.value) #%>%
  #round(2)
sim.slopes.exp

save(sim.slopes.exp, file = "sim.slopes.exp.Rda")
```


```{r}
#plot(sim.slope)

plot.sim.slope <- ggplot(sim.slope.tidy, aes(x = modx.value, y = exp(estimate))) +
  geom_point() +
  geom_errorbar(data = sim.slope.tidy, aes(ymin = exp(conf.low), ymax = exp(conf.high))) +
  scale_x_continuous(breaks = 0:11) +
  geom_abline(intercept = 1, slope = 0, linetype = "dashed") +
  labs(title = "Figure 3: Simple slopes for suicidal ideation by total gender affirmation \ninteraction, 2015 US Transgender Survey",
       x = "Total Affirmation Value",
       y = "Slope of Trans-Based Discrimination") +
  theme(text = element_text(family = "Times New Roman", face = "bold"))
plot.sim.slope
```



```{r}
# Interaction model - affirm total cat only - rm
glm.ixn.affirm.cat.rm <- svyglm(suicidal ~ disc.trans*affirm.total.cat +
                                  disc.non.trans +
                              age +
                              race +
                              education +
                              poverty +
                              disability +
                              saab +
                              passing,
                             family = quasibinomial(),
                             data   = data.design,
                             design = USTS.design)

summ(glm.ixn.affirm.cat.rm, exp = T, confint = T)



sink("ModelIxnAffirmCatRm.txt")
summ(glm.ixn.affirm.cat.rm, exp = T, confint = T)
sink()
```

```{r}
sim.slope.cat <- sim_slopes(glm.ixn.affirm.cat.rm, pred = disc.trans, modx = affirm.total.cat)
sim.slope.cat
tidy(sim.slope.cat)
```


```{r}
# Intermediate model - discrimination only - rm
glm.int.disc.rm <- svyglm(suicidal ~ disc.trans +
                            disc.non.trans +
                            age +
                            race +
                            education +
                            poverty +
                            disability +
                            saab +
                            passing,
                             family = quasibinomial(),
                             data   = data.design,
                             design = USTS.design)

summ(glm.int.disc.rm, exp = T, confint = T)



sink("ModelIntDiscRm.txt")
summ(glm.int.disc.rm, exp = T, confint = T)
sink()
```


```{r}
# Intermediate model - affirm total only - rm
glm.int.affirm.rm <- svyglm(suicidal ~ disc.trans +
                              affirm.total +
                              disc.non.trans +
                            age +
                            race +
                            education +
                            poverty +
                            disability +
                            saab +
                            passing,
                             family = quasibinomial(),
                             data   = data.design,
                             design = USTS.design)

summ(glm.int.affirm.rm, exp = T, confint = T)



sink("ModelIntAffirmRm.txt")
summ(glm.int.affirm.rm, exp = T, confint = T)
sink()
```

```{r}
# Intermediate model - affirm total cat only - rm
glm.int.affirm.cat.rm <- svyglm(suicidal ~ disc.trans +
                                  affirm.total.cat +
                                  disc.non.trans +
                            age +
                            race +
                            education +
                            poverty +
                            disability +
                            saab +
                            passing,
                             family = quasibinomial(),
                             data   = data.design,
                             design = USTS.design)

summ(glm.int.affirm.cat.rm, exp = T, confint = T)



sink("ModelIntAffirmCatRm.txt")
summ(glm.int.affirm.cat.rm, exp = T, confint = T)
sink()
```

```{r}
# Intermediate model - affirm all - rm
glm.int.all.rm <- svyglm(suicidal ~ disc.trans +
                            affirm.family +
                        affirm.provider +
                        affirm.id.name +
                        affirm.id.gender +
                        affirm.hormone +
                        affirm.med.surg +
                            disc.non.trans +
                            age +
                            race +
                            education +
                            poverty +
                            disability +
                            saab +
                            passing,
                             family = quasibinomial(),
                             data   = data.design,
                             design = USTS.design)

summ(glm.int.all.rm, exp = T, confint = T)



sink("ModelIntAllRm.txt")
summ(glm.int.all.rm, exp = T, confint = T)
sink()
```

```{r}
# Interaction model - affirm family only - rm
glm.ixn.family.rm <- svyglm(suicidal ~ disc.trans*affirm.family +
                              disc.non.trans +
                              age +
                              race +
                              education +
                              poverty +
                              disability +
                              saab +
                              passing,
                             family = quasibinomial(),
                             data   = data.design,
                             design = USTS.design)

summ(glm.ixn.family.rm, exp = T, confint = T)



sink("ModelIxnFamilyRm.txt")
summ(glm.ixn.family.rm, exp = T, confint = T)
sink()
```

```{r}
# Interaction model - affirm provider only - rm
glm.ixn.provider.rm <- svyglm(suicidal ~ disc.trans*affirm.provider +
                                disc.non.trans +
                              age +
                              race +
                              education +
                              poverty +
                              disability +
                              saab +
                              passing,
                             family = quasibinomial(),
                             data   = data.design,
                             design = USTS.design)

summ(glm.ixn.provider.rm, exp = T, confint = T)



sink("ModelIxnProviderRm.txt")
summ(glm.ixn.provider.rm, exp = T, confint = T)
sink()
```

```{r}
# Interaction model - affirm IDs name only - rm
glm.ixn.id.name.rm <- svyglm(suicidal ~ disc.trans*affirm.id.name +
                               disc.non.trans +
                              age +
                              race +
                              education +
                              poverty +
                              disability +
                              saab +
                              passing,
                             family = quasibinomial(),
                             data   = data.design,
                             design = USTS.design)

summ(glm.ixn.id.name.rm, exp = T, confint = T)



sink("ModelIxnIDsNameRm.txt")
summ(glm.ixn.id.name.rm, exp = T, confint = T)
sink()
```

```{r}
# Interaction model - affirm IDs gender only - rm
glm.ixn.id.gender.rm <- svyglm(suicidal ~ disc.trans*affirm.id.gender +
                                 disc.non.trans +
                              age +
                              race +
                              education +
                              poverty +
                              disability +
                              saab +
                              passing,
                             family = quasibinomial(),
                             data   = data.design,
                             design = USTS.design)

summ(glm.ixn.id.gender.rm, exp = T, confint = T)



sink("ModelIxnIDsGenderRm.txt")
summ(glm.ixn.id.gender.rm, exp = T, confint = T)
sink()
```

```{r}
# Interaction model - affirm IDs hormone only - rm
glm.ixn.hormone.rm <- svyglm(suicidal ~ disc.trans*affirm.hormone +
                               disc.non.trans +
                              age +
                              race +
                              education +
                              poverty +
                              disability +
                              saab +
                              passing,
                             family = quasibinomial(),
                             data   = data.design,
                             design = USTS.design)

summ(glm.ixn.hormone.rm, exp = T, confint = T)



sink("ModelIxnHormoneRm.txt")
summ(glm.ixn.hormone.rm, exp = T, confint = T)
sink()
```

```{r}
# Interaction model - affirm medical/surgical only - rm
glm.ixn.med.rm <- svyglm(suicidal ~ disc.trans*affirm.med.surg +
                           disc.non.trans +
                              age +
                              race +
                              education +
                              poverty +
                              disability +
                              saab +
                              passing,
                             family = quasibinomial(),
                             data   = data.design,
                             design = USTS.design)

summ(glm.ixn.med.rm, exp = T, confint = T)



sink("ModelIxnMedRm.txt")
summ(glm.ixn.med.rm, exp = T, confint = T)
sink()
```

# Create Tables 1-3

```{r}
#USTSsvy <- svydesign(ids = ~1,
#                     weights = ~SURVEYFULLWEIGHT,
#                     nest = FALSE,
#                     data = data.all)
vars <- c("suicidal", "disc.trans", "disc.non.trans", "affirm.total", "affirm.total.cat", "affirm.family", "affirm.provider", "affirm.id.name", "affirm.id.gender", "affirm.hormone", "affirm.med.surg", "age", "race",  "education", "poverty", "citizenship", "religious", "military", "disability", "saab", "passing", "outness", "orientation")
fvars <- c("suicidal", "affirm.total.cat",  "affirm.family", "affirm.provider", "affirm.id.name", "affirm.id.gender", "affirm.hormone", "affirm.med.surg", "race", "education", "poverty", "citizenship", "religious", "military",  "disability", "saab", "passing", "outness", "orientation")
```


```{r}
tab1 <- svyCreateTableOne(data = USTS.design,
                          vars = vars,
                          factorVars = fvars,
                          
                          includeNA = FALSE,
                          test=FALSE)
summary(tab1)

print(tab1, showAllLevels = T, varLabels = T)

# t1 <- kable(print(tab1,
#                    showAllLevels = TRUE,
#                    varLabels = TRUE,
#                    printToggle = FALSE,
#                    noSpaces = TRUE,
#                    catDigits=1,
#                    contDigits=1),
#       align = 'lc',
#       format = "latex",
#       col.names = c("", "Overall"),
#       booktabs = TRUE,
#       caption=paste("Descriptive statistics for participants in",
#                                  "2015 U.S. Transgender Survey."))
# 
# t1 %>% kable_styling(latex_options = c("striped", "hold_position")) %>% save_kable("Table 1.pdf", keep_tex = TRUE)
```

```{r}
sink("Table1Summary.txt")
print(tab1, showAllLevels = T, varLabels = T)
sink()
```

```{r}
write.csv(tab1, file = "Table1.csv")
```



```{r}
tab2 <- svyCreateTableOne(data = USTS.design,
                          vars = setdiff(vars,c("disc.trans.quantile", "disc.trans")),
                          factorVars = setdiff(fvars,c("disc.trans.quantile")),
                          strata = "disc.trans.quantile",
                          test = TRUE)
summary(tab2)
# t2 <- kable(print(tab2,
#                    showAllLevels = TRUE,
#                    varLabels = TRUE,
#                    printToggle = FALSE,
#                    noSpaces = TRUE,
#                    catDigits=1,
#                    contDigits=1),
#       align = 'lc',
#       format = "latex",
#       col.names = c("", levels(data.all$disc.trans.quantile),"p-value","Test Statistic"),
#       booktabs = TRUE,
#       caption=paste("Descriptive statistics for participants in",
#                                  "2015 U.S. Transgender Survey",
#                                  "stratified by median Trans Discrimination score."))
# t2 %>% kable_styling(latex_options = c("striped", "hold_position")) %>% save_kable("Table 2.pdf", keep_tex = TRUE)
```

```{r}
sink("Table2Summary.txt")
print(tab2, showAllLevels = T, varLabels = T)
sink()
```

```{r}
svyby(~disc.trans, ~suicidal, USTS.design, svymean, na.rm = T)
svychisq(~disc.trans + suicidal, USTS.design, statistic = "F")

svycor(~disc.trans + affirm.total, USTS.design)$cors
```

```{r}
svychisq(~disc.trans + citizenship, USTS.design, statistic = "F")
```



```{r}
svyby(~disc.trans, ~affirm.total.cat, USTS.design, svymean, na.rm = T)
svychisq(~disc.trans + affirm.total.cat, USTS.design, statistic = "F")
```

```{r}
svycor(~disc.trans + age, USTS.design)$cors
```

```{r}
svyby(~disc.trans, ~poverty, USTS.design, svymean, na.rm = T)
svychisq(~disc.trans + poverty, USTS.design, statistic = "F")
```


```{r}
svyby(~disc.trans, ~citizenship, USTS.design, svymean, na.rm = T)
svyby(~disc.trans, ~passing, USTS.design, svymean, na.rm = T)
svyby(~disc.trans, ~outness, USTS.design, svymean, na.rm = T)
svyby(~disc.trans, ~orientation, USTS.design, svymean, na.rm = T)
svyby(~disc.trans, ~race, USTS.design, svymean, na.rm = T)
svyby(~disc.trans, ~age, USTS.design, svymean, na.rm = T)
svyby(~disc.trans, ~education, USTS.design, svymean, na.rm = T)
svyby(~disc.trans, ~disability, USTS.design, svymean, na.rm = T)
svyby(~disc.trans, ~military, USTS.design, svymean, na.rm = T)
svyby(~disc.trans, ~religious, USTS.design, svymean, na.rm = T)
svyby(~disc.trans, ~gender, USTS.design, svymean, na.rm = T)
svyby(~disc.trans, ~poverty, USTS.design, svymean, na.rm = T)
svyby(~disc.trans, ~disc.non.trans, USTS.design, svymean, na.rm = T)
svyby(~disc.trans, ~affirm.intper.fam, USTS.design, svymean, na.rm = T)
svyby(~disc.trans, ~affirm.intper.non.fam, USTS.design, svymean, na.rm = T)
svyby(~disc.trans, ~affirm.struct.inst, USTS.design, svymean, na.rm = T)
svyby(~disc.trans, ~affirm, USTS.design, svymean, na.rm = T)
```
```{r}

a <- svyby(~disc.trans, ~K6severe, USTS.design, svymean, na.rm = T)
sink("Table2Raw.txt")
print(a)
sink()
```



```{r}
tab3 <- svyCreateTableOne(data = USTS.design,
                          vars = setdiff(vars,c("suicidal")),
                          factorVars = setdiff(fvars,c("suicidal")),
                          strata = "suicidal",
                          test=TRUE)
summary(tab3)

print(tab3, showAllLevels = T, varLabels = T)
# t3 <- kable(print(tab3,
#                    showAllLevels = TRUE,
#                    varLabels = TRUE,
#                    printToggle = FALSE,
#                    noSpaces = TRUE,
#                    catDigits=1,
#                    contDigits=1),
#       align = 'lc',
#       col.names = c("", levels(data.all$K6severe),"p-value","Test Statistic"),
#       booktabs = TRUE,
#       format = "latex",
#       caption=paste("Descriptive statistics for participants in",
#                                  "2015 U.S. Transgender Survey",
#                                  "stratified by severe Kessler 6 score."))
# t3 %>% kable_styling(latex_options = c("striped", "hold_position")) %>% save_kable("Table 3.pdf", keep_tex = TRUE)
```

```{r}
sink("Table3Summary.txt")
print(tab3, showAllLevels = T, varLabels = T)
sink()
```

```{r}
svychisq(~suicidal + disc.trans, USTS.design, statistic = "F")
svychisq(~suicidal + affirm.total, USTS.design, statistic = "F")
svychisq(~suicidal + disc.non.trans, USTS.design, statistic = "F")
svychisq(~suicidal + age, USTS.design, statistic = "F")

svyby(~suicidal, ~affirm.total.cat, USTS.design, svymean, na.rm = T)*100
svychisq(~suicidal + affirm.total.cat, USTS.design, statistic = "Chisq")

svyby(~suicidal, ~affirm.family, USTS.design, svymean, na.rm = T)*100
svychisq(~suicidal + affirm.family, USTS.design, statistic = "Chisq")

svyby(~suicidal, ~affirm.provider, USTS.design, svymean, na.rm = T)*100
svychisq(~suicidal + affirm.provider, USTS.design, statistic = "Chisq")
```

```{r}
svyby(~suicidal, ~affirm.total.cat, USTS.design, svymean, na.rm = T)*100
svychisq(~suicidal + affirm.total.cat, USTS.design, statistic = "Chisq")
```


```{r}
svyby(~suicidal, ~poverty, USTS.design, svymean, na.rm = T)*100
svychisq(~suicidal + poverty, USTS.design, statistic = "Chisq")
```
